### ISSUE TITLE
프로젝트 관리

### ISSUE THREAD

**Issue by parkeugene** [parkeugene/on-rise#12]

**Comment by neverlish** [comment]
- [ ] 이미지
- [ ] 제목
- [ ] 설명
- [ ] 원문 링크
- [ ] 번역 링크
- [ ] 번역자(팀)
- [ ] 최종목표
- [ ] 프로젝트 분야
- [ ] 참여방법
- [ ] 좋아요
- [ ] 시작일자
- [ ] 종료일자
- [ ] 진행상태
- [ ] 조회수
- [ ] Contact email
