### ISSUE TITLE
write README

### ISSUE THREAD

**Issue by neverlish** [parkeugene/on-rise#2]

**Comment by parkeugene** [comment]
README에 들어갈 내용입니다.
프로젝트 소개
프로젝트 설치
프로젝트 참여 
워크 플로우 Github flow
- 이슈 등록
- 브랜치 생성
- 브랜치 push
- 브랜치 PR
- 코드 리뷰
- 브랜치 배포
- master에 merge

**Comment by neverlish** [comment]
프로젝트 설치에 관한 사항
- contributor 가 자유롭게 추가될 수 있게
- fork 후
- clone 후 해야 할 사항들(bundle install, rake, rails s)
- ruby version, rails version
- branch 를 만들어서 이거를 pull request
- project 실행 방법
