### ISSUE TITLE
번역진행중인 프로젝트 정보 조사

### ISSUE THREAD

**Issue by mentalveritas** [parkeugene/on-rise#4]
우선 프로그래밍 관련된것 위주로 자료 조사
체계적인 조사를 위해 구글드라이브에 시트하나
생성해서 관리

**Comment by parkeugene** [comment]
레일스 가이드 guides.rorlab.org

**Comment by parkeugene** [comment]
레일스 튜토리얼

**Comment by parkeugene** [comment]
rorlab.org

**Comment by mentalveritas** [comment]
Go 언어 한글 번역(http://codingnuri.com/golang-book/)
Rust 한글화 프로젝트(https://www.penflip.com/sarojaba/rust-doc-korean)
Swift 개발문서 한글화(http://swift.leantra.kr/)
