### ISSUE TITLE
Sign up Controller

### ISSUE THREAD

**Issue by mentalveritas** [parkeugene/on-rise#9]
방향성 의견이 필요합니다.
회원 관리 기능 구축을 할때

1. devise잼을 활용하여 구축한다.
2. 직접 구축해 본다.

comment로 달아주시면 감사합니다 :)

**Comment by neverlish** [comment]
저는 1번이 좋을 듯 하지만, 일요일 행아웃 할 때 같이 이야기해봤으면 합니다 ^^

**Comment by parkeugene** [comment]
저도 1번

**Comment by mentalveritas** [comment]
넵 1번으로..!! 일요일 행아웃 참석 못해서 죄송합니다..ㅠㅠ

**Comment by mentalveritas** [comment]
넵 저도 Devise 젬 활용이 좋은거 같습니다.
